wp:
  image: wordpress
  ports:
    - 9999:80
  links:
    - db:mysql
  volumes:
    - ./dist:/var/www/html/wp-content/themes/wp-mini

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: secret

